server:
  port: 9002
spring:
  application:
    name: test-movie
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9003/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
